apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mae-demo
  namespace: mae
  description: Tanzu Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=mae-demo'
    'github.com/project-slug': 'Mpluya/tap-innerloop-demoware'
spec:
  type: service
  lifecycle: experimental
  owner: team-a
